<?php

/**
 * Implements hook_theme().
 */
function banner_module_theme($existing, $type, $theme, $path)
{
    return [
        'my_template' => [
            'variables' => [
                'test_var' => ''
            ],
        ],
        'banner' => [
            'variables' => [
                'position' => ''
            ]
        ],
        'test' => [
            'variables' => [
                'entity' => [],
                'abc' => []
            ]
        ]
    ];
}
